name: npm publish

on:
  push:
    # Sequence of patterns matched against refs/heads
    #branches:
    #  - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn lerna bootstrap
      - run: yarn test
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > /home/runner/work/eslint-config-sentry/eslint-config-sentry/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn lerna publish from-git --yes --registry="https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
